server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - kafka.yml
      - logging.yml
      - monitoring.yml

kafka:
  consumers:
    audit-log:
      group-id: audit-log-consumer-group
      source-topic: audit.log-events.v1
      dlq-topic: audit.log-events.dlq.v1

    metrics-aggregation:
      group-id: product-metrics-consumer-group
      source-topic: product.signal-events.v1
      dlq-topic: product.signal-events.dlq.v1



---
spring:
  config:
    activate:
      on-profile: local, test

server:
  port: 8084

management:
  server:
    port: 8085

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8084

management:
  server:
    port: 8085

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false